[build]
  # The folder where the build assets are placed
  publish = "build"

  # Install dependencies and start the application using gunicorn
  command = "pip install -r requirements.txt && gunicorn -b :$PORT wsgi:app"

[context.production.environment]
  # Setting Flask environment variables
  FLASK_ENV = "production"
  FLASK_APP = "app.py"
  PORT = "5000"  # Make sure PORT is a string

# Optional: Add custom redirects
[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301
