[build]
  # Define the publish directory where static assets (like CSS, JS) should go.
  # Flask might not have this, but this is necessary for Netlify to work.
  publish = "build"

  # Command to install dependencies and run the app with Gunicorn.
  # You can change the app path if needed.
  command = "pip install -r requirements.txt && gunicorn -b :$PORT wsgi:app"

[context.production.environment]
  # Flask settings for the production environment
  FLASK_ENV = "production"
  FLASK_APP = "app.py"
  PORT = 5000

# Optional: Add custom redirects if necessary for specific routes or behavior
[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301
